# Generated by Django 4.1.4 on 2023-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creater_id',
            field=models.IntegerField(null=True),
        ),
    ]
