# Generated by Django 4.1.4 on 2022-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0002_alter_profile_adress_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
