# Generated by Django 4.1.4 on 2022-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(to='rhinoApi.product'),
        ),
    ]
