# Generated by Django 4.1.4 on 2022-12-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0005_user_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('delicered', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='rhinoApi.product')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ordered',
            field=models.ManyToManyField(to='rhinoApi.order'),
        ),
    ]
