# Generated by Django 4.1.4 on 2023-01-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0007_order_ordernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='creater_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='rev',
            field=models.ManyToManyField(null=True, to='rhinoApi.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rhinoApi.reviewimages'),
        ),
    ]
