# Generated by Django 4.1.4 on 2023-01-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0008_reviewimages_rename_name_review_creater_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.AddField(
            model_name='reviewimages',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rhinoApi.review'),
        ),
    ]
