# Generated by Django 4.1.4 on 2023-01-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0010_alter_reviewimages_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
