# Generated by Django 4.1.4 on 2023-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.ManyToManyField(blank=True, to='rhinoApi.review'),
        ),
    ]
