# Generated by Django 4.1.4 on 2023-01-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0012_alter_product_rev'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=30)),
                ('news_header', models.CharField(max_length=40)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rhinoApi.product')),
            ],
        ),
    ]
