# Generated by Django 4.1.4 on 2023-02-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinoApi', '0013_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creater_pfp',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
